In [96]:
#helping out @hikinghack
#see https://twitter.com/HikingHack/status/1481353359294701570

import numpy as np
np.random.seed(42)

In [159]:
#create two dummy datasets of length N
N = 30

#create the two datasets a dnd b - each datasets has 1000 rows and 2 columns with random numbers between 1 and 10
a = np.random.randint(40, 44, size=(N, 2))
b = np.random.randint(40, 44, size=(N, 2))
ix = np.array(np.arange(N))

In [160]:
#add two columns to the our dataset. The first column is the index of the row (From 0 to 199) and the second column is 0 for dataset a and 1 for dataset b
a = np.c_[ix, np.zeros(N), a]
b = np.c_[ix, np.ones(N), b]

In [161]:
#now add the two datasets together
c = np.r_[a,b]

In [162]:
#sort by the last two column
c = c[np.lexsort((c[:,3], c[:,2]))]
c

array([[26.,  0., 40., 40.],
       [28.,  0., 40., 40.],
       [22.,  1., 40., 40.],
       [18.,  0., 40., 41.],
       [ 7.,  1., 40., 41.],
       [ 6.,  1., 40., 42.],
       [19.,  1., 40., 42.],
       [20.,  1., 40., 42.],
       [26.,  1., 40., 42.],
       [29.,  1., 40., 42.],
       [ 1.,  0., 40., 43.],
       [22.,  0., 40., 43.],
       [ 4.,  1., 40., 43.],
       [ 9.,  1., 40., 43.],
       [ 3.,  0., 41., 40.],
       [ 9.,  0., 41., 40.],
       [23.,  0., 41., 40.],
       [12.,  1., 41., 40.],
       [ 6.,  0., 41., 41.],
       [ 7.,  0., 41., 41.],
       [12.,  0., 41., 41.],
       [14.,  0., 41., 42.],
       [21.,  0., 41., 42.],
       [21.,  1., 41., 42.],
       [23.,  1., 41., 42.],
       [ 8.,  0., 41., 43.],
       [11.,  0., 41., 43.],
       [13.,  0., 41., 43.],
       [28.,  1., 41., 43.],
       [27.,  0., 42., 40.],
       [29.,  0., 42., 40.],
       [10.,  1., 42., 40.],
       [10.,  0., 42., 41.],
       [ 8.,  1., 42., 41.],
       [14.,  

In [163]:
#creates a sibling array shifted by one row up
c1 = np.roll(c,-1, axis=0)
c1

array([[28.,  0., 40., 40.],
       [22.,  1., 40., 40.],
       [18.,  0., 40., 41.],
       [ 7.,  1., 40., 41.],
       [ 6.,  1., 40., 42.],
       [19.,  1., 40., 42.],
       [20.,  1., 40., 42.],
       [26.,  1., 40., 42.],
       [29.,  1., 40., 42.],
       [ 1.,  0., 40., 43.],
       [22.,  0., 40., 43.],
       [ 4.,  1., 40., 43.],
       [ 9.,  1., 40., 43.],
       [ 3.,  0., 41., 40.],
       [ 9.,  0., 41., 40.],
       [23.,  0., 41., 40.],
       [12.,  1., 41., 40.],
       [ 6.,  0., 41., 41.],
       [ 7.,  0., 41., 41.],
       [12.,  0., 41., 41.],
       [14.,  0., 41., 42.],
       [21.,  0., 41., 42.],
       [21.,  1., 41., 42.],
       [23.,  1., 41., 42.],
       [ 8.,  0., 41., 43.],
       [11.,  0., 41., 43.],
       [13.,  0., 41., 43.],
       [28.,  1., 41., 43.],
       [27.,  0., 42., 40.],
       [29.,  0., 42., 40.],
       [10.,  1., 42., 40.],
       [10.,  0., 42., 41.],
       [ 8.,  1., 42., 41.],
       [14.,  1., 42., 41.],
       [24.,  

In [164]:
#subtract the two
d = c1-c
#then take only the last two columns 
e = d[:,2:4] 
e

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 1., -3.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 1., -3.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 1., -3.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,

In [165]:
#now sum the columns row by row
f = np.sum(e, axis=1)

#find the indeces of the rows where the sum is 0
idx = np.where(f==0)


In [166]:
#now show the rows that match
r = c1[idx]
r

array([[28.,  0., 40., 40.],
       [22.,  1., 40., 40.],
       [ 7.,  1., 40., 41.],
       [19.,  1., 40., 42.],
       [20.,  1., 40., 42.],
       [26.,  1., 40., 42.],
       [29.,  1., 40., 42.],
       [22.,  0., 40., 43.],
       [ 4.,  1., 40., 43.],
       [ 9.,  1., 40., 43.],
       [ 9.,  0., 41., 40.],
       [23.,  0., 41., 40.],
       [12.,  1., 41., 40.],
       [ 7.,  0., 41., 41.],
       [12.,  0., 41., 41.],
       [21.,  0., 41., 42.],
       [21.,  1., 41., 42.],
       [23.,  1., 41., 42.],
       [11.,  0., 41., 43.],
       [13.,  0., 41., 43.],
       [28.,  1., 41., 43.],
       [29.,  0., 42., 40.],
       [10.,  1., 42., 40.],
       [ 8.,  1., 42., 41.],
       [14.,  1., 42., 41.],
       [24.,  1., 42., 41.],
       [27.,  1., 42., 41.],
       [ 3.,  1., 42., 42.],
       [ 5.,  1., 42., 42.],
       [18.,  1., 42., 42.],
       [25.,  1., 42., 42.],
       [17.,  0., 42., 43.],
       [16.,  1., 42., 43.],
       [20.,  0., 43., 40.],
       [25.,  

In [158]:
#you may sort back by the first two columns now if that helps visualisation
r = r[np.lexsort((r[:,0], r[:,1]))]
r

array([[ 2.,  0., 42., 43.],
       [ 6.,  0., 42., 42.],
       [14.,  0., 43., 43.],
       [15.,  0., 40., 40.],
       [16.,  0., 43., 41.],
       [17.,  0., 41., 40.],
       [18.,  0., 43., 40.],
       [19.,  0., 40., 42.],
       [ 0.,  1., 42., 42.],
       [ 1.,  1., 41., 43.],
       [ 2.,  1., 43., 43.],
       [ 3.,  1., 43., 42.],
       [ 4.,  1., 41., 41.],
       [ 5.,  1., 42., 41.],
       [ 6.,  1., 42., 43.],
       [ 7.,  1., 42., 43.],
       [ 8.,  1., 43., 40.],
       [10.,  1., 42., 42.],
       [11.,  1., 40., 40.],
       [12.,  1., 42., 41.],
       [13.,  1., 43., 40.],
       [14.,  1., 43., 41.],
       [15.,  1., 41., 41.],
       [17.,  1., 40., 41.],
       [18.,  1., 43., 43.],
       [19.,  1., 42., 43.]])

In [ ]:
r